name: CI
on:
  # Trigger the workflow on push or pull request,
  push:
    paths:
      - index.js
  pull_request:
    paths:
      - index.js
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx